-- MySQL Script generated by MySQL Workbench
-- Sun May 25 01:44:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TheStrange
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TheStrange` ;

-- -----------------------------------------------------
-- Schema TheStrange
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TheStrange` ;
-- -----------------------------------------------------
-- Schema Usuario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Usuario` ;

-- -----------------------------------------------------
-- Schema Usuario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Usuario` ;
USE `TheStrange` ;

-- -----------------------------------------------------
-- Table `TheStrange`.`Rasgo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Rasgo` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Rasgo` (
  `nombre` VARCHAR(45) NOT NULL,
  `descripion` LONGTEXT NULL DEFAULT NULL,
  `trasferible` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`HabilidadRasgo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`HabilidadRasgo` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`HabilidadRasgo` (
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `rango` INT NULL DEFAULT NULL,
  `coste` INT NULL DEFAULT NULL,
  `reserva` VARCHAR(45) NULL DEFAULT NULL,
  `Rasgo_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_HabilidadRasgo_Rasgo1_idx` (`Rasgo_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_HabilidadRasgo_Rasgo1`
    FOREIGN KEY (`Rasgo_nombre`)
    REFERENCES `TheStrange`.`Rasgo` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Efecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Efecto` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Efecto` (
  `idEfecto` INT NOT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `sugerencia` VARCHAR(255) NULL DEFAULT NULL,
  `Rasgo_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEfecto`),
  INDEX `fk_Efecto_Rasgo1_idx` (`Rasgo_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Efecto_Rasgo1`
    FOREIGN KEY (`Rasgo_nombre`)
    REFERENCES `TheStrange`.`Rasgo` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Recursion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Recursion` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Recursion` (
  `nombre` VARCHAR(45) NOT NULL,
  `resumen` VARCHAR(255) NULL DEFAULT NULL,
  `nivel` INT NULL DEFAULT NULL,
  `conexionTheStrange` VARCHAR(255) NULL DEFAULT NULL,
  `conexionTierra` VARCHAR(255) NULL DEFAULT NULL,
  `forma` VARCHAR(225) NULL,
  `chispa` VARCHAR(45) NULL DEFAULT NULL,
  `divisa` VARCHAR(45) NULL DEFAULT NULL,
  `mapa` VARCHAR(225) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`RasgoRecursion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`RasgoRecursion` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`RasgoRecursion` (
  `Recursion_nombre` VARCHAR(45) NOT NULL,
  `Rasgo_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Recursion_nombre`, `Rasgo_nombre`),
  INDEX `fk_RasgoRecursion_Recursion1_idx` (`Recursion_nombre` ASC) VISIBLE,
  INDEX `fk_RasgoRecursion_Rasgo1_idx` (`Rasgo_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_RasgoRecursion_Recursion1`
    FOREIGN KEY (`Recursion_nombre`)
    REFERENCES `TheStrange`.`Recursion` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RasgoRecursion_Rasgo1`
    FOREIGN KEY (`Rasgo_nombre`)
    REFERENCES `TheStrange`.`Rasgo` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`listaTipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`listaTipos` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`listaTipos` (
  `idTipos` INT NOT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Apartado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Apartado` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Apartado` (
  `idApartado` INT NOT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `texto` LONGTEXT NULL DEFAULT NULL,
  `listaTipos_idTipos` INT NOT NULL,
  `Recursion_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idApartado`),
  INDEX `fk_Apartado_listaTipos1_idx` (`listaTipos_idTipos` ASC) VISIBLE,
  INDEX `fk_Apartado_Recursion1_idx` (`Recursion_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Apartado_listaTipos1`
    FOREIGN KEY (`listaTipos_idTipos`)
    REFERENCES `TheStrange`.`listaTipos` (`idTipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apartado_Recursion1`
    FOREIGN KEY (`Recursion_nombre`)
    REFERENCES `TheStrange`.`Recursion` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Arma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Arma` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Arma` (
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(225) NULL DEFAULT NULL,
  `daño` INT NULL DEFAULT NULL,
  `reduccionDificultad` INT NULL DEFAULT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Armadura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Armadura` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Armadura` (
  `nombre` VARCHAR(45) NOT NULL,
  `costeVigor` INT NULL DEFAULT NULL,
  `reduccionVelocidad` INT NULL DEFAULT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Equipo` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Equipo` (
  `nombre` VARCHAR(45) NOT NULL,
  `precio` FLOAT NULL DEFAULT NULL,
  `nota` VARCHAR(255) NULL DEFAULT NULL,
  `Arma_nombre` VARCHAR(45) NULL,
  `Armadura_nombre` VARCHAR(45) NULL,
  `Recursion_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_Equipo_Arma1_idx` (`Arma_nombre` ASC) VISIBLE,
  INDEX `fk_Equipo_Armadura1_idx` (`Armadura_nombre` ASC) VISIBLE,
  INDEX `fk_Equipo_Recursion1_idx` (`Recursion_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Equipo_Arma1`
    FOREIGN KEY (`Arma_nombre`)
    REFERENCES `TheStrange`.`Arma` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_Armadura1`
    FOREIGN KEY (`Armadura_nombre`)
    REFERENCES `TheStrange`.`Armadura` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_Recursion1`
    FOREIGN KEY (`Recursion_nombre`)
    REFERENCES `TheStrange`.`Recursion` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Artefactos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Artefactos` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Artefactos` (
  `nombre` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(45) NULL DEFAULT NULL,
  `forma` VARCHAR(45) NULL DEFAULT NULL,
  `efecto` LONGTEXT NULL,
  `tiradaEfecto` LONGTEXT NULL,
  `agotamiento` VARCHAR(45) NULL,
  `Recursion_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_Artefactos_Recursion1_idx` (`Recursion_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Artefactos_Recursion1`
    FOREIGN KEY (`Recursion_nombre`)
    REFERENCES `TheStrange`.`Recursion` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Razas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Razas` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Razas` (
  `idRazas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(225) NULL DEFAULT NULL,
  PRIMARY KEY (`idRazas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`RazasRecursion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`RazasRecursion` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`RazasRecursion` (
  `Razas_idRazas` INT NOT NULL,
  `Recursion_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Razas_idRazas`, `Recursion_nombre`),
  INDEX `fk_RazasRecursion_Recursion1_idx` (`Recursion_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_RazasRecursion_Razas1`
    FOREIGN KEY (`Razas_idRazas`)
    REFERENCES `TheStrange`.`Razas` (`idRazas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RazasRecursion_Recursion1`
    FOREIGN KEY (`Recursion_nombre`)
    REFERENCES `TheStrange`.`Recursion` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Habilidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Habilidades` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Habilidades` (
  `idHabilidades` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Recursion_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHabilidades`),
  INDEX `fk_Habilidades_Recursion1_idx` (`Recursion_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Habilidades_Recursion1`
    FOREIGN KEY (`Recursion_nombre`)
    REFERENCES `TheStrange`.`Recursion` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Descriptor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Descriptor` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Descriptor` (
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `Vinculo` LONGTEXT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`DescriptorRecursion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`DescriptorRecursion` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`DescriptorRecursion` (
  `Descriptor_nombre` VARCHAR(45) NOT NULL,
  `Recursion_nombre` VARCHAR(45) NOT NULL,
  `mejora` VARCHAR(225) NULL DEFAULT NULL,
  PRIMARY KEY (`Descriptor_nombre`, `Recursion_nombre`),
  INDEX `fk_DescriptorRecursion_Recursion1_idx` (`Recursion_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_DescriptorRecursion_Descriptor1`
    FOREIGN KEY (`Descriptor_nombre`)
    REFERENCES `TheStrange`.`Descriptor` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DescriptorRecursion_Recursion1`
    FOREIGN KEY (`Recursion_nombre`)
    REFERENCES `TheStrange`.`Recursion` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Mejora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Mejora` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Mejora` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(225) NULL,
  `numero` INT NULL DEFAULT NULL,
  `reserva` VARCHAR(45) NULL DEFAULT NULL,
  `Descriptor_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Mejora_Descriptor1_idx` (`Descriptor_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Mejora_Descriptor1`
    FOREIGN KEY (`Descriptor_nombre`)
    REFERENCES `TheStrange`.`Descriptor` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`habilidadDescriptor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`habilidadDescriptor` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`habilidadDescriptor` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `incapacidad` TINYINT NULL DEFAULT NULL,
  `habilidad` TINYINT NULL,
  `Descriptor_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_habilidadDescriptor_Descriptor1_idx` (`Descriptor_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_habilidadDescriptor_Descriptor1`
    FOREIGN KEY (`Descriptor_nombre`)
    REFERENCES `TheStrange`.`Descriptor` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Clase` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Clase` (
  `nombre` VARCHAR(45) NOT NULL,
  `traslacion` VARCHAR(45) NULL DEFAULT NULL,
  `minimoDispositivos` INT NULL DEFAULT NULL,
  `descripcion` VARCHAR(225) NULL DEFAULT NULL,
  `vinculos` LONGTEXT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Poderes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Poderes` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Poderes` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(225) NULL DEFAULT NULL,
  `coste` INT NULL DEFAULT NULL,
  `rango` INT NULL DEFAULT NULL,
  `proeza` TINYINT NULL DEFAULT NULL,
  `Clase_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_HabilidadesClase_Clase1_idx` (`Clase_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_HabilidadesClase_Clase1`
    FOREIGN KEY (`Clase_nombre`)
    REFERENCES `TheStrange`.`Clase` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Caracteristicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Caracteristicas` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Caracteristicas` (
  `idCaracteristicas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `reserva` VARCHAR(45) NULL DEFAULT NULL,
  `Ventaja` VARCHAR(45) NULL,
  `Clase_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCaracteristicas`),
  INDEX `fk_Caracteristicas_Clase1_idx` (`Clase_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Caracteristicas_Clase1`
    FOREIGN KEY (`Clase_nombre`)
    REFERENCES `TheStrange`.`Clase` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Dispositivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Dispositivo` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Dispositivo` (
  `idDispositivo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `nivel` VARCHAR(45) NULL,
  `efecto` LONGTEXT NULL DEFAULT NULL,
  `efectosTiradas` VARCHAR(225) NULL,
  PRIMARY KEY (`idDispositivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`FormasDispositivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`FormasDispositivo` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`FormasDispositivo` (
  `Dispositivo_idDispositivo` INT NOT NULL,
  `Recursion_nombre` VARCHAR(45) NOT NULL,
  `aspecto` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_FormasDispositivo_Dispositivo1_idx` (`Dispositivo_idDispositivo` ASC) VISIBLE,
  INDEX `fk_FormasDispositivo_Recursion1_idx` (`Recursion_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_FormasDispositivo_Dispositivo1`
    FOREIGN KEY (`Dispositivo_idDispositivo`)
    REFERENCES `TheStrange`.`Dispositivo` (`idDispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FormasDispositivo_Recursion1`
    FOREIGN KEY (`Recursion_nombre`)
    REFERENCES `TheStrange`.`Recursion` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Criatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Criatura` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Criatura` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Nivel` INT NULL DEFAULT NULL,
  `descripcion` LONGTEXT NULL DEFAULT NULL,
  `motivacion` VARCHAR(225) NULL DEFAULT NULL,
  `entorno` VARCHAR(45) NULL DEFAULT NULL,
  `salud` INT NULL DEFAULT NULL,
  `daño` INT NULL DEFAULT NULL,
  `movimiento` VARCHAR(45) NULL DEFAULT NULL,
  `combate` LONGTEXT NULL DEFAULT NULL,
  `iteraccion` VARCHAR(225) NULL DEFAULT NULL,
  `uso` VARCHAR(45) NULL DEFAULT NULL,
  `botin` VARCHAR(45) NULL DEFAULT NULL,
  `Recursion_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`),
  INDEX `fk_Criatura_Recursion1_idx` (`Recursion_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Criatura_Recursion1`
    FOREIGN KEY (`Recursion_nombre`)
    REFERENCES `TheStrange`.`Recursion` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`ley`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`ley` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`ley` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(225) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`LeyRecursion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`LeyRecursion` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`LeyRecursion` (
  `ley_id` INT NOT NULL,
  `Recursion_nombre` VARCHAR(45) NOT NULL,
  INDEX `fk_LeyRecursion_ley1_idx` (`ley_id` ASC) VISIBLE,
  INDEX `fk_LeyRecursion_Recursion1_idx` (`Recursion_nombre` ASC) VISIBLE,
  PRIMARY KEY (`ley_id`, `Recursion_nombre`),
  CONSTRAINT `fk_LeyRecursion_ley1`
    FOREIGN KEY (`ley_id`)
    REFERENCES `TheStrange`.`ley` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LeyRecursion_Recursion1`
    FOREIGN KEY (`Recursion_nombre`)
    REFERENCES `TheStrange`.`Recursion` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`Conexion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`Conexion` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`Conexion` (
  `idConexion` INT NOT NULL,
  `descripcion` VARCHAR(225) NULL DEFAULT NULL,
  `Rasgo_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idConexion`),
  INDEX `fk_Conexion_Rasgo1_idx` (`Rasgo_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Conexion_Rasgo1`
    FOREIGN KEY (`Rasgo_nombre`)
    REFERENCES `TheStrange`.`Rasgo` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheStrange`.`CapacidadEspecial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheStrange`.`CapacidadEspecial` ;

CREATE TABLE IF NOT EXISTS `TheStrange`.`CapacidadEspecial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` LONGTEXT NULL,
  `Razas_idRazas` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CapacidadEspecial_Razas1_idx` (`Razas_idRazas` ASC) VISIBLE,
  CONSTRAINT `fk_CapacidadEspecial_Razas1`
    FOREIGN KEY (`Razas_idRazas`)
    REFERENCES `TheStrange`.`Razas` (`idRazas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Usuario` ;

-- -----------------------------------------------------
-- Table `Usuario`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `contraseña` VARCHAR(128) NULL,
  `token` VARCHAR(345) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`Manual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`Manual` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`Manual` (
  `id` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `imagen` VARCHAR(225) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`Campaña`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`Campaña` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`Campaña` (
  `idCampaña` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(225) NULL,
  `imagen` VARCHAR(225) NULL,
  `Manual_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCampaña`),
  INDEX `fk_Campaña_Manual1_idx` (`Manual_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Campaña_Manual1`
    FOREIGN KEY (`Manual_nombre`)
    REFERENCES `Usuario`.`Manual` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`Ficha_TheStrange`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`Ficha_TheStrange` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`Ficha_TheStrange` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `clase` VARCHAR(45) NULL,
  `experiencia` INT NULL,
  `esfuerzo` INT NULL,
  `limiteDispositivos` INT NULL,
  `recuperacion` VARCHAR(10) NULL,
  `trasfondo` BLOB NULL,
  `descriptor` VARCHAR(45) NULL,
  `vinculoDescriptor` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Manual_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ficha_TheStrange_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Ficha_TheStrange_Manual1_idx` (`Manual_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Ficha_TheStrange_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Usuario`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ficha_TheStrange_Manual1`
    FOREIGN KEY (`Manual_nombre`)
    REFERENCES `Usuario`.`Manual` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`UsuarioCampaña`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`UsuarioCampaña` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`UsuarioCampaña` (
  `Usuario_idUsuario` INT NOT NULL,
  `Campaña_idCampaña` INT NOT NULL,
  `Ficha_TheStrange_id` INT NOT NULL,
  INDEX `fk_UsuarioCampaña_Ficha_TheStrange1_idx` (`Ficha_TheStrange_id` ASC) VISIBLE,
  INDEX `fk_UsuarioCampaña_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_UsuarioCampaña_Campaña1_idx` (`Campaña_idCampaña` ASC) VISIBLE,
  PRIMARY KEY (`Usuario_idUsuario`, `Campaña_idCampaña`),
  CONSTRAINT `fk_UsuarioCampaña_Ficha_TheStrange1`
    FOREIGN KEY (`Ficha_TheStrange_id`)
    REFERENCES `Usuario`.`Ficha_TheStrange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioCampaña_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Usuario`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioCampaña_Campaña1`
    FOREIGN KEY (`Campaña_idCampaña`)
    REFERENCES `Usuario`.`Campaña` (`idCampaña`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`Mejora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`Mejora` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`Mejora` (
  `idMejora` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(225) NULL,
  PRIMARY KEY (`idMejora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`Caracteristicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`Caracteristicas` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`Caracteristicas` (
  `nombre` VARCHAR(45) NOT NULL,
  `reservaMax` INT NULL,
  `reservaAct` INT NULL,
  `ventaja` INT NULL,
  `Ficha_TheStrange_id` INT NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_Caracteristicas_Ficha_TheStrange1_idx` (`Ficha_TheStrange_id` ASC) VISIBLE,
  CONSTRAINT `fk_Caracteristicas_Ficha_TheStrange1`
    FOREIGN KEY (`Ficha_TheStrange_id`)
    REFERENCES `Usuario`.`Ficha_TheStrange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`Notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`Notas` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`Notas` (
  `idNotas` INT NOT NULL,
  `texto` VARCHAR(225) NULL,
  `Ficha_TheStrange_id` INT NOT NULL,
  PRIMARY KEY (`idNotas`),
  INDEX `fk_Notas_Ficha_TheStrange1_idx` (`Ficha_TheStrange_id` ASC) VISIBLE,
  CONSTRAINT `fk_Notas_Ficha_TheStrange1`
    FOREIGN KEY (`Ficha_TheStrange_id`)
    REFERENCES `Usuario`.`Ficha_TheStrange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`ListaDispositivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`ListaDispositivos` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`ListaDispositivos` (
  `nombre` VARCHAR(45) NOT NULL,
  `forma` VARCHAR(45) NULL,
  `efecto` VARCHAR(225) NULL,
  `Ficha_TheStrange_id` INT NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_ListaDispositivos_Ficha_TheStrange1_idx` (`Ficha_TheStrange_id` ASC) VISIBLE,
  CONSTRAINT `fk_ListaDispositivos_Ficha_TheStrange1`
    FOREIGN KEY (`Ficha_TheStrange_id`)
    REFERENCES `Usuario`.`Ficha_TheStrange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`Recursion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`Recursion` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`Recursion` (
  `idRecursion` INT NOT NULL,
  `rasgo` VARCHAR(45) NULL,
  `dinero` INT NULL,
  `armadura` INT NULL,
  `apariencia` BLOB NULL,
  `raza` VARCHAR(45) NULL,
  `sexo` VARCHAR(10) NULL,
  `actual` TINYINT NULL,
  `Ficha_TheStrange_id` INT NOT NULL,
  PRIMARY KEY (`idRecursion`),
  INDEX `fk_Recursion_Ficha_TheStrange1_idx` (`Ficha_TheStrange_id` ASC) VISIBLE,
  CONSTRAINT `fk_Recursion_Ficha_TheStrange1`
    FOREIGN KEY (`Ficha_TheStrange_id`)
    REFERENCES `Usuario`.`Ficha_TheStrange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`Competencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`Competencias` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`Competencias` (
  `nombre` VARCHAR(45) NOT NULL,
  `especializado` TINYINT NULL,
  `descripcion` VARCHAR(225) NULL,
  `Ficha_TheStrange_id` INT NULL,
  `Recursion_idRecursion` INT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_Competencias_Ficha_TheStrange1_idx` (`Ficha_TheStrange_id` ASC) VISIBLE,
  INDEX `fk_Competencias_Recursion1_idx` (`Recursion_idRecursion` ASC) VISIBLE,
  CONSTRAINT `fk_Competencias_Ficha_TheStrange1`
    FOREIGN KEY (`Ficha_TheStrange_id`)
    REFERENCES `Usuario`.`Ficha_TheStrange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Competencias_Recursion1`
    FOREIGN KEY (`Recursion_idRecursion`)
    REFERENCES `Usuario`.`Recursion` (`idRecursion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`Equipo` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`Equipo` (
  `idEquipo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(225) NULL,
  `daño` INT NULL,
  `modificador` INT NULL,
  `arma` TINYINT NULL,
  `Recursion_idRecursion` INT NOT NULL,
  PRIMARY KEY (`idEquipo`),
  INDEX `fk_Equipo_Recursion1_idx` (`Recursion_idRecursion` ASC) VISIBLE,
  CONSTRAINT `fk_Equipo_Recursion1`
    FOREIGN KEY (`Recursion_idRecursion`)
    REFERENCES `Usuario`.`Recursion` (`idRecursion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`Habilidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`Habilidades` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`Habilidades` (
  `nombre` VARCHAR(45) NOT NULL,
  `coste` VARCHAR(45) NULL,
  `descripcion` VARCHAR(225) NULL,
  `Ficha_TheStrange_id` INT NULL,
  `Competencias_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_Habilidades_Ficha_TheStrange1_idx` (`Ficha_TheStrange_id` ASC) VISIBLE,
  INDEX `fk_Habilidades_Competencias1_idx` (`Competencias_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Habilidades_Ficha_TheStrange1`
    FOREIGN KEY (`Ficha_TheStrange_id`)
    REFERENCES `Usuario`.`Ficha_TheStrange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Habilidades_Competencias1`
    FOREIGN KEY (`Competencias_nombre`)
    REFERENCES `Usuario`.`Competencias` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`TiradasRecuperacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`TiradasRecuperacion` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`TiradasRecuperacion` (
  `id` INT NOT NULL,
  `tiempo` VARCHAR(45) NULL,
  `descansado` TINYINT NULL,
  `Ficha_TheStrange_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TiradasRecuperacion_Ficha_TheStrange1_idx` (`Ficha_TheStrange_id` ASC) VISIBLE,
  CONSTRAINT `fk_TiradasRecuperacion_Ficha_TheStrange1`
    FOREIGN KEY (`Ficha_TheStrange_id`)
    REFERENCES `Usuario`.`Ficha_TheStrange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`IndicadorDaño`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`IndicadorDaño` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`IndicadorDaño` (
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `cansado` TINYINT NULL,
  `Ficha_TheStrange_id` INT NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_IndicadorDaño_Ficha_TheStrange1_idx` (`Ficha_TheStrange_id` ASC) VISIBLE,
  CONSTRAINT `fk_IndicadorDaño_Ficha_TheStrange1`
    FOREIGN KEY (`Ficha_TheStrange_id`)
    REFERENCES `Usuario`.`Ficha_TheStrange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`.`FichaMejora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario`.`FichaMejora` ;

CREATE TABLE IF NOT EXISTS `Usuario`.`FichaMejora` (
  `Mejora_idMejora` INT NOT NULL,
  `Ficha_TheStrange_id` INT NOT NULL,
  `cogida` TINYINT NULL,
  INDEX `fk_FichaMejora_Mejora1_idx` (`Mejora_idMejora` ASC) VISIBLE,
  INDEX `fk_FichaMejora_Ficha_TheStrange1_idx` (`Ficha_TheStrange_id` ASC) VISIBLE,
  PRIMARY KEY (`Ficha_TheStrange_id`, `Mejora_idMejora`),
  CONSTRAINT `fk_FichaMejora_Mejora1`
    FOREIGN KEY (`Mejora_idMejora`)
    REFERENCES `Usuario`.`Mejora` (`idMejora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FichaMejora_Ficha_TheStrange1`
    FOREIGN KEY (`Ficha_TheStrange_id`)
    REFERENCES `Usuario`.`Ficha_TheStrange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
