/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextArea;

/**
 *
 * @author Diurno
 */
public class Vista extends javax.swing.JFrame {

    /**
     * En la vista pongo el layout a null para evitarme problemas con los layout,
     * y añado las imagenes que necesito
     */
    public Vista() {
        initComponents();
        this.setLayout(null);

        Image imgLogo = new ImageIcon("assets/logo2.png").getImage();
        ImageIcon logo = new ImageIcon(imgLogo.getScaledInstance(lLogo.getWidth(), lLogo.getHeight(), Image.SCALE_SMOOTH));
        lLogo.setIcon(logo);
        
        Image img = new ImageIcon("assets/fondo.png").getImage();
        ImageIcon fondo = new ImageIcon(img.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH));
        lFondo.setIcon(fondo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbClases = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lHitDie = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCompetencias = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaSalvacion = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cbEqupamiento = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textaNiveles = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textaHechizo = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jFuerza = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDestre = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jConstitu = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jCarisma = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jInt = new javax.swing.JLabel();
        jSab = new javax.swing.JLabel();
        lFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 310, 120));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 91, 29));

        cbClases.setBackground(new java.awt.Color(231, 221, 199));
        cbClases.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionClase2(evt);
            }
        });
        getContentPane().add(cbClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 122, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hit Dies");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 18));

        lHitDie.setBackground(new java.awt.Color(231, 221, 199));
        lHitDie.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lHitDie.setForeground(new java.awt.Color(255, 255, 255));
        lHitDie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lHitDie.setText("1DX");
        lHitDie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lHitDie, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 80, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Competencias");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        listCompetencias.setBackground(new java.awt.Color(231, 221, 199));
        listCompetencias.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(222, 160, 23)));
        jScrollPane1.setViewportView(listCompetencias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, 160));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tiradas de Salvación");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        listaSalvacion.setBackground(new java.awt.Color(231, 221, 199));
        listaSalvacion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(222, 160, 23)));
        jScrollPane2.setViewportView(listaSalvacion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 133, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Packs de equipamiento inicial");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        cbEqupamiento.setBackground(new java.awt.Color(231, 221, 199));
        cbEqupamiento.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(222, 160, 23)));
        cbEqupamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionPack(evt);
            }
        });
        jScrollPane3.setViewportView(cbEqupamiento);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 290, 234));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Niveles");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        textaNiveles.setBackground(new java.awt.Color(231, 221, 199));
        textaNiveles.setColumns(20);
        textaNiveles.setRows(5);
        jScrollPane4.setViewportView(textaNiveles);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 150, 470, 380));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hechizos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, -1, -1));

        textaHechizo.setBackground(new java.awt.Color(231, 221, 199));
        textaHechizo.setColumns(20);
        textaHechizo.setRows(5);
        textaHechizo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(222, 160, 23)));
        jScrollPane5.setViewportView(textaHechizo);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 290, 349));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fuerza");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        jFuerza.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jFuerza.setForeground(new java.awt.Color(255, 255, 255));
        jFuerza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFuerza.setText("0");
        jFuerza.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jFuerza.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jFuerza, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 90, 90));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Destreza");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 550, 80, -1));

        jDestre.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jDestre.setForeground(new java.awt.Color(255, 255, 255));
        jDestre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDestre.setText("0");
        jDestre.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jDestre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jDestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 90, 90));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Contitución");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 550, 110, -1));

        jConstitu.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jConstitu.setForeground(new java.awt.Color(255, 255, 255));
        jConstitu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jConstitu.setText("0");
        jConstitu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jConstitu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jConstitu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 90, 90));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Carisma");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 680, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Sabiduría");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 680, -1, -1));

        jCarisma.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jCarisma.setForeground(new java.awt.Color(255, 255, 255));
        jCarisma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCarisma.setText("0");
        jCarisma.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jCarisma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jCarisma, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 680, 90, 90));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Inteligen.");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, -1, -1));

        jInt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jInt.setForeground(new java.awt.Color(255, 255, 255));
        jInt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInt.setText("0");
        jInt.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jInt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 680, 90, 90));

        jSab.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jSab.setForeground(new java.awt.Color(255, 255, 255));
        jSab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSab.setText("0");
        jSab.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jSab.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jSab, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, 90, 90));
        getContentPane().add(lFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 820));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionClase2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionClase2
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionClase2

    private void seleccionPack(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionPack
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionPack
    
/**
 *
 * Este método esta para poder tener un ActionLisener que me permitira controlar
 * el evento de selección de clase desde el controlador.
 */
    public void seleccionClase2(ActionListener listen) {                                
        cbClases.addActionListener(listen);
    }  

    
    public JComboBox<String> getCbClases() {
        return cbClases;
    }

    public JLabel getlHitDie() {
        return lHitDie;
    }

    public JList<String> getListCompetencias() {
        return listCompetencias;
    }

    public JList<String> getListaSalvacion() {
        return listaSalvacion;
    }

    public JList<String> getCbEqupamiento() {
        return cbEqupamiento;
    }

    public JTextArea getTextaNiveles() {
        return textaNiveles;
    }

    public JTextArea getTextaHechizo() {
        return textaHechizo;
    }

    public JLabel getjCarisma() {
        return jCarisma;
    }

    public JLabel getjConstitu() {
        return jConstitu;
    }

    public JLabel getjDestre() {
        return jDestre;
    }

    public JLabel getjFuerza() {
        return jFuerza;
    }

    public JLabel getjInt() {
        return jInt;
    }

    public JLabel getjSab() {
        return jSab;
    }

    



    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbClases;
    private javax.swing.JList<String> cbEqupamiento;
    private javax.swing.JLabel jCarisma;
    private javax.swing.JLabel jConstitu;
    private javax.swing.JLabel jDestre;
    private javax.swing.JLabel jFuerza;
    private javax.swing.JLabel jInt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jSab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lFondo;
    private javax.swing.JLabel lHitDie;
    private javax.swing.JLabel lLogo;
    private javax.swing.JList<String> listCompetencias;
    private javax.swing.JList<String> listaSalvacion;
    private javax.swing.JTextArea textaHechizo;
    private javax.swing.JTextArea textaNiveles;
    // End of variables declaration//GEN-END:variables
}
